// schemas/OrderSchema.js
export const OrderSchema = {
  request: {
    required: [
      "name",
      "email",
      "phone",
      "paymentMethod",
      "items",
      "reservationDate",
      "schedule",
    ],
    types: {
      name: "string",
      email: "string",
      phone: "string", // Cambiado a string (por el +52 o ceros iniciales)
      reservationDate: "string", // Tu nuevo campo estrella
      schedule: "string", // El bloque: "07:00-09:00", etc.
      paymentMethod: "object",
      items: "array",
    },
  },
  response: {
    // Fields generated by server at level 5
    base: [
      "id_order",
      "status",
      "expiresAt",
      "createdAt", // Important for audit
      "_id",
    ],
    // Campos que se llenan solo cuando PayPal confirma el dinero
    payment: ["capturedAt"],
  },
};
