export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';

export const ALL_PRODUCTS_LOAD_START = 'ALL_PRODUCTS_LOAD_START';
export const ALL_PRODUCTS_SET_STATE = 'ALL_PRODUCTS_SET_STATE';
export const PRODUCTS_SET_STATE = 'PRODUCTS_SET_STATE';

export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_ERROR = 'ORDER_CREATE_ERROR';
export const ORDER_CREATE_NETWORK_ERROR = 'ORDER_CREATE_NETWORK_ERROR';
export const ORDER_CREATE_SERVER_ERROR = 'ORDER_CREATE_SERVER_ERROR';
export const ORDER_CREATE_LOADING = 'ORDER_CREATE_LOADING';
export const ORDER_CREATE_INPUT_VALIDATION_ERROR = 'ORDER_CREATE_INPUT_VALIDATION_ERROR';
export const ORDER_CREATE_VALIDATION_ERROR = 'ORDER_CREATE_VALIDATION_ERROR';

export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS';
export const ORDER_GET_ERROR = 'ORDER_GET_ERROR';
export const ORDER_GET_NETWORK_ERROR = 'ORDER_GET_NETWORK_ERROR';
export const ORDER_GET_SERVER_ERROR = 'ORDER_GET_SERVER_ERROR';
export const ORDER_GET_LOADING = 'ORDER_GET_LOADING';
export const ORDER_GET_INPUT_VALIDATION_ERROR = 'ORDER_GET_INPUT_VALIDATION_ERROR';
export const ORDER_GET_VALIDATION_ERROR = 'ORDER_GET_VALIDATION_ERROR';
export const ORDER_GET_ORDER_NOT_FOUND = 'ORDER_GET_ORDER_NOT_FOUND';
export const ORDER_PAYPAL_CREATE_LOADING = 'ORDER_PAYPAL_CREATE_LOADING';

export const SET_CONTACT_INFO = 'SET_CONTACT_INFO';
export const CLEAR_CONTACT_INFO = 'CLEAR_CONTACT_INFO';
export const SET_DATE = 'SET_DATE';
export const SET_SCHEDULE = 'SET_SCHEDULE';
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD';







